Repository CensorKeepers/FilterAI, pull requests merged in 2024-03, with the labels that each got.

#21 Kullanıcı tarafından açılan tablar ve url'lerin kontrolü sağlandı.
  .vscode/launch.json
  .vscode/settings.json
  config/ChromeController.json
  config/EdgeController.json
  config/FirefoxController.json
  run.sh
  src/ChromeController.py
  src/ContentFetcher.py
  src/EdgeController.py
  src/FirefoxController.py
  src/TextExtractor.py
  src/URLTracker.py
  str.sh
Labels: feature

#24 Refresh algılanması implement edildi.
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  requirements.txt
  src/ChromeController.py
  src/ContentFetcher.py
  src/EdgeController.py
  src/FirefoxController.py
  src/JSHandler.py
  src/TextExtractor.py
  src/URLTracker.py
Labels: feature, refactor

#25 Örnek filtreleme işlemi, ChatGPT ile mesajlaşma ve siteyi kullanıcıdan filtreleme bitene kadar gizleme.
  .gitignore
  requirements.txt
  src/CensorDecider.py
  src/ContentFetcher.py
  src/JSHandler.py
  src/SentenceExtractor.py
  src/TextExtractor.py
  src/URLTracker.py
Labels: feature, discussion

#26 LLM kararı ile kelime filtreleme
  src/CensorDecider.py
  src/ContentFetcher.py
  src/DetoxifySentences.py
  src/SentenceExtractor.py
  src/TextExtractor.py
  src/main.py
Labels: done, feature, discussion

#28 Filtrelenecek kelimelerde CSS değişikliği sağlandı.
  run.sh
  src/ContentFetcher.py
  src/DetoxifySentences.py
  src/JSHandler.py
  src/SentenceExtractor.py
Labels: done, feature

#29 kodda bazı kısımlar verimlileştirildi, hata kontrolleri yapıldı
  .gitignore
  src/ContentFetcher.py
  src/JSHandler.py
  src/SentenceExtractor.py
  src/TextExtractor.py
Labels: done, feature, bugfix
